//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : BuildingBox
	/// Data Source    : localhost
	/// Server Version : 9.6.1
	/// </summary>
	public partial class BuildingBoxDB : LinqToDB.Data.DataConnection
	{
		public ITable<Ticket>         Tickets         { get { return this.GetTable<Ticket>(); } }
		public ITable<TicketMessage>  TicketMessages  { get { return this.GetTable<TicketMessage>(); } }
		public ITable<TicketWorkFlow> TicketWorkFlows { get { return this.GetTable<TicketWorkFlow>(); } }
		public ITable<User>           Users           { get { return this.GetTable<User>(); } }
		public ITable<UserContract>   UserContracts   { get { return this.GetTable<UserContract>(); } }

		public BuildingBoxDB()
		{
			InitDataContext();
		}

		public BuildingBoxDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="public", Name="Ticket")]
	public partial class Ticket
	{
		[PrimaryKey, Identity] public long      id            { get; set; } // bigint
		[Column,     Nullable] public DateTime? dtCreation    { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public DateTime? dtLog         { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public long?     fkUserOpen    { get; set; } // bigint
		[Column,     Nullable] public long?     fkTicketState { get; set; } // bigint
		[Column,     Nullable] public string    stProtocol    { get; set; } // character varying(9)
		[Column,     Nullable] public string    stTitle       { get; set; } // character varying(200)
		[Column,     Nullable] public string    stDescription { get; set; } // character varying(2000)
	}

	[Table(Schema="public", Name="TicketMessage")]
	public partial class TicketMessage
	{
		[PrimaryKey, Identity] public long      id        { get; set; } // bigint
		[Column,     Nullable] public long?     fkTicket  { get; set; } // bigint
		[Column,     Nullable] public long?     fkUser    { get; set; } // bigint
		[Column,     Nullable] public DateTime? dtLog     { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public string    stMessage { get; set; } // character varying(200)
	}

	[Table(Schema="public", Name="TicketWorkFlow")]
	public partial class TicketWorkFlow
	{
		[PrimaryKey, Identity] public long      id         { get; set; } // bigint
		[Column,     Nullable] public long?     fkTicket   { get; set; } // bigint
		[Column,     Nullable] public long?     fkOldState { get; set; } // bigint
		[Column,     Nullable] public long?     fkNewState { get; set; } // bigint
		[Column,     Nullable] public long?     fkUser     { get; set; } // bigint
		[Column,     Nullable] public DateTime? dtLog      { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public string    stMessage  { get; set; } // character varying(200)
	}

	[Table(Schema="public", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity] public long      id             { get; set; } // bigint
		[Column,     Nullable] public DateTime? dtCreation     { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public string    stClientName   { get; set; } // character varying(99)
		[Column,     Nullable] public long?     fkClientType   { get; set; } // bigint
		[Column,     Nullable] public long?     fkCountry      { get; set; } // bigint
		[Column,     Nullable] public string    stCityName     { get; set; } // character varying(200)
		[Column,     Nullable] public long?     fkDesiredGMT   { get; set; } // bigint
		[Column,     Nullable] public string    stPassword     { get; set; } // character varying(20)
		[Column,     Nullable] public string    stContactEmail { get; set; } // character varying(200)
	}

	[Table(Schema="public", Name="UserContract")]
	public partial class UserContract
	{
		[PrimaryKey, Identity] public long      id             { get; set; } // bigint
		[Column,     Nullable] public DateTime? dtCreation     { get; set; } // timestamp (6) without time zone
		[Column,     Nullable] public string    stProtocol     { get; set; } // character varying(200)
		[Column,     Nullable] public string    stDNS          { get; set; } // character varying(200)
		[Column,     Nullable] public long?     fkUser         { get; set; } // bigint
		[Column,     Nullable] public long?     fkContractType { get; set; } // bigint
		[Column,     Nullable] public long?     fkGMT          { get; set; } // bigint
		[Column,     Nullable] public long?     fkContinent    { get; set; } // bigint
		[Column,     Nullable] public long?     fkCountry      { get; set; } // bigint
		[Column,     Nullable] public long?     fkCity         { get; set; } // bigint
	}

	public static partial class TableExtensions
	{
		public static Ticket Find(this ITable<Ticket> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static TicketMessage Find(this ITable<TicketMessage> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static TicketWorkFlow Find(this ITable<TicketWorkFlow> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static User Find(this ITable<User> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static UserContract Find(this ITable<UserContract> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
